{
  "Launchpad": "https://bugs.launchpad.net/bugs/1428609",
  "Id": "1428609",
  "Gerrit": "https://review.openstack.org/161945",
  "IdGerrit": "161945",
  "IdCommit": "e75e2f14de49ff89bdcc4f0feffa0dcb5833482d",
  "Files": "cinder/volume/flows/manager/create_volume.py",
  "Lines_Inseted": "5",
  "Lines_Deleted": "4",
  "CommitParent": "35b1a03a4539d2e7c61d261ce800a241e603d65c",
  "Classification": "Bug",
  "KeywordsTitle": "Error typing, delete",
  "Description": "was using, since a patch, merged, replaced, affects, delete, log, error message, ",
  "KeywordsCommit": "Error trying, delete, Patch #133566 , partially changed, modified , was replaced. ",
  "Comments": "It's a bug report, after a patch when you are deleting something you find log errors"
}